oswestry_eng <- dplyr::tibble(
  id = c("id001", "id002", "id003", "id004", "id005", "id006",
         "id001", "id002", "id003", "id004", "id005", "id006"),
  Day = c("2022-07-12","2022-07-14","2022-07-25","2022-08-01","2022-08-06","2022-08-06",
          "2022-07-12","2022-07-14","2022-07-25","2022-08-01","2022-08-06","2022-08-06"),
  painIntensity = c("I have no pain at the moment","The pain is very mild at the moment","The pain is moderate at the moment","The pain is fairly severe at the moment","The pain is very severe at the moment","The pain is the worst imaginable at the moment",
                    NA,NA,NA,NA,NA,NA),
  personalCare = c("I can look after myself normally without causing extra pain","I can look after myself normally but it causes extra pain","It is painful to look after myself and I am slow and careful","I need some help but manage most of my personal care","I need help every day in most aspects of self-care","I do not get dressed, I wash with difficulty and stay in bed","I can look after myself normally without causing extra pain",NA,NA,NA,NA,NA),
  lifting = c("I can lift heavy weights without extra pain","I can lift heavy weights but it gives extra pain","Pain prevents me from lifting heavy weights off the floor, but I can manage if they are conveniently placed eg. on a table","Pain prevents me from lifting heavy weights, but I can manage light to medium weights if they are conveniently positioned","I can lift very light weights","I cannot lift or carry anything at all","I can lift heavy weights without extra pain","I can lift heavy weights but it gives extra pain",NA,NA,NA,NA),
  walking = c("Pain does not prevent me walking any distance","Pain prevents me from walking more than 1 mile","Pain prevents me from walking more than 1/4 mile","Pain prevents me from walking more than 100 yards","I can only walk using a stick or crutches","I am in bed most of the time and have to crawl to the toilet.","Pain does not prevent me walking any distance","Pain prevents me from walking more than 1 mile","Pain prevents me from walking more than 1/4 mile",NA,NA,NA),
  sitting = c("I can sit in any chair as long as I like","I can only sit in my favourite chair as long as I like","Pain prevents me sitting more than one hour","Pain prevents me from sitting more than 1/2 hour","Pain prevents me from sitting more than 10 minutes","Pain prevents me from sitting at all","I can sit in any chair as long as I like","I can only sit in my favourite chair as long as I like","Pain prevents me sitting more than one hour","Pain prevents me from sitting more than 1/2 hour",NA,NA),
  standing = c("I can stand as long as I want without extra pain","I can stand as long as I want but it gives me extra pain","Pain prevents me from standing for more than 1 hour","Pain prevents me from standing for more than 1/2 hour","Pain prevents me from standing for more than 10 minutes","Pain prevents me from standing at all","I can stand as long as I want without extra pain","I can stand as long as I want but it gives me extra pain","Pain prevents me from standing for more than 1 hour","Pain prevents me from standing for more than 1/2 hour","Pain prevents me from standing for more than 10 minutes",NA),
  sleeping = c("My sleep is never disturbed by pain","My sleep is occasionally disturbed by pain","Because of pain I have less than 6 hours sleep","Because of pain I have less than 4 hours sleep","Because of pain I have less than 2 hours sleep","Pain prevents me from sleeping at all","My sleep is never disturbed by pain","My sleep is occasionally disturbed by pain","Because of pain I have less than 6 hours sleep","Because of pain I have less than 4 hours sleep","Because of pain I have less than 2 hours sleep","Pain prevents me from sleeping at all"),
  sexLife = c("My sex life is normal and causes no extra pain","My sex life is normal but causes some extra pain","My sex life is nearly normal but is very painful","My sex life is severely restricted by pain","My sex life is nearly absent because of pain","Pain prevents any sex life at all","My sex life is normal and causes no extra pain","My sex life is normal but causes some extra pain","My sex life is nearly normal but is very painful","My sex life is severely restricted by pain","My sex life is nearly absent because of pain","Pain prevents any sex life at all"),
  socialLife = c("My social life is normal and gives me no extra pain","My social life is normal but increases the degree of pain","Pain has no significant effect on my social life apart from limiting my more energetic interests eg, sport","Pain has restricted my social life and I do not go out as often","Pain has restricted my social life to home","I have no social life because of pain","My social life is normal and gives me no extra pain","My social life is normal but increases the degree of pain","Pain has no significant effect on my social life apart from limiting my more energetic interests eg, sport","Pain has restricted my social life and I do not go out as often","Pain has restricted my social life to home","I have no social life because of pain"),
  travelling = c("I can travel anywhere without pain","I can travel anywhere but it gives extra pain","Pain is bad but I manage journeys over two hours","Pain restricts me to journeys of less than one hour","Pain restricts me to short necessary journeys under 30 minutes","Pain prevents me from travelling except to receive treatment","I can travel anywhere without pain","I can travel anywhere but it gives extra pain","Pain is bad but I manage journeys over two hours","Pain restricts me to journeys of less than one hour","Pain restricts me to short necessary journeys under 30 minutes","Pain prevents me from travelling except to receive treatment"),
  scored.pain = c(0,1,2,3,4,5,NA,NA,NA,NA,NA,NA),
  scored.personalCare = c(0,1,2,3,4,5,0,NA,NA,NA,NA,NA),
  scored.lifting = c(0,1,2,3,4,5,0,1,NA,NA,NA,NA),
  scored.walking = c(0,1,2,3,4,5,0,1,2,NA,NA,NA),
  scored.sitting = c(0,1,2,3,4,5,0,1,2,3,NA,NA),
  scored.standing = c(0,1,2,3,4,5,0,1,2,3,4,NA),
  scored.sleeping = c(0,1,2,3,4,5,0,1,2,3,4,5),
  scored.sexLife = c(0,1,2,3,4,5,0,1,2,3,4,5),
  scored.socialLife = c(0,1,2,3,4,5,0,1,2,3,4,5),
  scored.travelling = c(0,1,2,3,4,5,0,1,2,3,4,5),
  numerator = c(0,10,20,30,40,50,0,8,14,18,20,20),
  denominator = c(50,50,50,50,50,50,45,40,35,30,25,20),
  oswestry = c(0,20,40,60,80,100,0,20,40,60,80,100)
  )

oswestry_fr <- dplyr::tibble(
  id = c("id001", "id002", "id003", "id004", "id005", "id006",
         "id001", "id002", "id003", "id004", "id005", "id006"),
  Day = c("2022-07-12","2022-07-14","2022-07-25","2022-08-01","2022-08-06","2022-08-06",
          "2022-07-12","2022-07-14","2022-07-25","2022-08-01","2022-08-06","2022-08-06"),
  painIntensity = c("Je n�ai pas de douleur en ce moment.","La douleur est tre?s le?ge?re en ce moment.","La douleur est mode?re?e en ce moment.","La douleur est assez forte en ce moment.","La douleur est tre?s forte en ce moment.","La douleur est au-dela? de toute description.",NA,NA,NA,NA,NA,NA),
  personalCare = c("Je peux faire mes soins personnels sans augmenter la douleur.","Je peux faire mes soins personnels mais cela augmente la douleur.","C�est douloureux de faire mes soins personnels et je les fais lentement et avec pre?caution.","J�ai besoin d�un peu d�aide mais je peux faire la plupart de mes soins personnels.","J�ai besoin d�aide tous les jours pour la plupart de mes soins personnels.","Je ne m�habille pas, je me lave avec difficulte? et je reste au lit.","Je peux faire mes soins personnels sans augmenter la douleur.",NA,NA,NA,NA,NA),
  lifting = c("Je peux soulever des objets lourds sans augmenter la douleur.","Je peux soulever des objets lourds mais cela augmente la douleur.","La douleur m�empe?che de soulever des objets lourds a? partir du sol mais je peux les soulever s�ils sont bien place?s, par exemple sur une table.","              La douleur m�empe?che de soulever des objets lourds mais je peux soulever des objets le?gers ou moyens s�ils sont bien place?s.","Je peux seulement soulever des objets tre?s le?gers.","Je ne peux rien soulever ni transporter.","Je peux soulever des objets lourds sans augmenter la douleur.","Je peux soulever des objets lourds mais cela augment la douleur.",NA,NA,NA,NA),
  walking = c("La douleur ne m�empe?che pas de marcher peu importe la distance.","La douleur m�empe?che de marcher plus d�une mille (1,5 kilome?tres).","La douleur m�empe?che de marcher plus d�un demi-mille (0.75 kilome?tre).","La douleur m�empe?che de marcher plus de 100 verges (100 me?tres).","Je ne peux marcher seulement a? l�aide d�une canne ou de be?quilles.","Je suis au lit la plupart du temps et je dois ramper pour aller aux toilettes.","La douleur ne m�empe?che pas de marcher peu importe la distance.","La douleur m�empe?che de marcher plus d�une mille (1,5 kilome?tres).","La douleur m�empe?che de marcher plus d�un demi-mille (0.75 kilome?tre).",NA,NA,NA),
  sitting = c("Je peux m�asseoir sur n�importe quel fauteuil aussi longtemps que je le veux.","Je peux m�asseoir sur mon fauteuil pre?fe?re? aussi longtemps que je le veux.","La douleur m�empe?che de m�asseoir plus d�une heure.","La douleur m�empe?che de m�asseoir plus d�une demi-heure.","La douleur m�empe?che de m�asseoir plus de 10 minutes.","La douleur m�empe?che comple?tement de m�asseoir.","Je peux m�asseoir sur n�importe quel fauteuil aussi longtemps que je le veux.","Je peux m�asseoir sur mon fauteuil pre?fe?re? aussi longtemps que je le veux.","La douleur m�empe?che de m�asseoir plus d�une heure.","La douleur m�empe?che de m�asseoir plus d�une demi-heure.",NA,NA),
  standing = c("Je peux me tenir debout aussi longtemps que je le veux sans augmenter la douleur.","Je peux me tenir debout aussi longtemps que je le veux mais cela augmente la douleur.","La douleur m�empe?che de me tenir debout plus d�une heure.","La douleur m�empe?che de me tenir debout plus d�une demi-heure.","La douleur m�empe?che de me tenir debout plus de 10 minutes.","La douleur m�empe?che comple?tement de me tenir debout.","Je peux me tenir debout aussi longtemps que je le veux sans augmenter la douleur.","Je peux me tenir debout aussi longtemps que j le veux mais cela augmente la douleur.","La douleur m�empe?che de me tenir debout plus d�une heure.","La douleur m�empe?che de me tenir debout plus d�une demi-heure.","La douleur m�empe?che de me tenir debout plus de 10 minutes.",NA),
  sleeping = c("Mon sommeil n�est jamais perturbe? par la douleur.","Mon sommeil est parfois perturbe? par la douleur.","A? cause de la douleur, j�ai moins de 6 heures de sommeil.","A? cause de la douleur, j�ai moins de 4 heures de sommeil.","A? cause de la douleur, j�ai moins de 2 heures de sommeil.","La douleur m�empe?che comple?tement de dormir.","Mon sommeil n�est jamais perturbe? par la douleur.","Mon sommeil est parfois perturbe? par la douleur.","A? cause de la douleur, j�ai moins de 6 heures de sommeil.","A? cause de la douleur, j�ai moins de 4 heures de sommeil.","A? cause de la douleur, j�ai moins de 2 heures de sommeil.","La douleur m�empe?che comple?tement de dormir."),
  sexLife = c("Ma vie sexuelle est normale et elle ne me cause pas d�augmentation de la douleur.","Ma vie sexuelle est normale mais elle cause une certaine augmentation de la douleur.","Ma vie sexuelle est presque normale mais elle est tre?s douloureuse.","Ma vie sexuelle est tre?s limite?e par la douleur.","Ma vie sexuelle est presqu�absente a? cause de la douleur.","La douleur empe?che toute vie sexuelle.","Ma vie sexuelle est normale et elle ne me cause pas d�augmentation de la douleur.","Ma vie sexuelle est normale mais elle cause une certaine augmentation de la douleur.","Ma vie sexuelle est presque normale mais elle est tre?s douloureuse.","Ma vie sexuelle est tre?s limite?e par la douleur.","Ma vie sexuelle est presqu�absente a? cause de la douleur.","La douleur empe?che toute vie sexuelle."),
  socialLife = c("Ma vie sociale est normale et ne me cause pas d�augmentation de la douleur.","Ma vie sociale est normale mais elle augmente le niveau de la douleur.","La douleur n�a pas d�effet important sur ma vie sociale a? part de limiter mes activite?s les plus vigoureuses, par exemple, le sport, etc.","La douleur a limite? ma vie sociale et je ne sors plus autant qu�avant.","La douleur a limite? ma vie sociale a? mon domicile.","Je n�ai pas de vie sociale a? cause de la douleur.","Ma vie sociale est normale et ne me cause pas d�augmentation de la douleur.","Ma vie sociale est normale mais elle augmente le niveau de la douleur.","La douleur n�a pas d�effet important sur ma vie sociale a? part de limiter mes activite?s les plus vigoureuses, par exemple, le sport, etc.","La douleur a limite? ma vie sociale et je ne sors plus autant qu�avant.","La douleur a limite? ma vie sociale a? mon domicile.","Je n�ai pas de vie sociale a? cause de la douleur."),
  travelling = c("Je peux me de?placer n�importe ou? sans douleur.","Je peux me de?placer n�importe ou? mais cela augmente la douleur.","La douleur est forte mais je peux me de?placer plus de deux heures.","La douleur me limite a? des de?placements de moins de 30 minutes.","La douleur me limite a? de courts de?placements ne?cessaires de moins de 30 minutes.","La douleur m�empe?che de me de?placer sauf pour recevoir des traitements.","Je peux me de?placer n�importe ou? sans douleur.","Je peux me de?placer n�importe ou? mais cela augmente la douleur.","La douleur est forte mais je peux me de?placer plus de deux heures.","La douleur me limite a? des de?placements de moins de 30 minutes.","La douleur me limite a? de courts de?placements ne?cessaires de moins de 30 minutes.","La douleur m�empe?che de me de?placer sauf pour recevoir des traitements."),
  scored.pain = c(0,1,2,3,4,5,NA,NA,NA,NA,NA,NA),
  scored.personalCare = c(0,1,2,3,4,5,0,NA,NA,NA,NA,NA),
  scored.lifting = c(0,1,2,3,4,5,0,1,NA,NA,NA,NA),
  scored.walking = c(0,1,2,3,4,5,0,1,2,NA,NA,NA),
  scored.sitting = c(0,1,2,3,4,5,0,1,2,3,NA,NA),
  scored.standing = c(0,1,2,3,4,5,0,1,2,3,4,NA),
  scored.sleeping = c(0,1,2,3,4,5,0,1,2,3,4,5),
  scored.sexLife = c(0,1,2,3,4,5,0,1,2,3,4,5),
  scored.socialLife = c(0,1,2,3,4,5,0,1,2,3,4,5),
  scored.travelling = c(0,1,2,3,4,5,0,1,2,3,4,5),
  numerator = c(0,10,20,30,40,50,0,8,14,18,20,20),
  denominator = c(50,50,50,50,50,50,45,40,35,30,25,20),
  oswestry = c(0,20,40,60,80,100,0,20,40,60,80,100)
)


## Creating data frames column by colum with the clipboard
## Copy  the colum you want, then run the two lines below
## Paste the output in a vector in base::data.frame()

#x <- readClipboard()
#cat('"',x, sep = '","','"') # For strings
#cat(x, sep = ",")           # For numbers
